# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/inference_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/inference_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/inference_server/CMakeFiles /workspace/inference_server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/inference_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named triton-server

# Build rule for target.
triton-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triton-server
.PHONY : triton-server

# fast build rule for target.
triton-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triton-server.dir/build.make CMakeFiles/triton-server.dir/build
.PHONY : triton-server/fast

#=============================================================================
# Target rules for targets named curl

# Build rule for target.
curl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl
.PHONY : curl

# fast build rule for target.
curl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/curl.dir/build.make _deps/repo-third-party-build/CMakeFiles/curl.dir/build
.PHONY : curl/fast

#=============================================================================
# Target rules for targets named grpc-repo

# Build rule for target.
grpc-repo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpc-repo
.PHONY : grpc-repo

# fast build rule for target.
grpc-repo/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/grpc-repo.dir/build.make _deps/repo-third-party-build/CMakeFiles/grpc-repo.dir/build
.PHONY : grpc-repo/fast

#=============================================================================
# Target rules for targets named nlohmann-json

# Build rule for target.
nlohmann-json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nlohmann-json
.PHONY : nlohmann-json

# fast build rule for target.
nlohmann-json/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/nlohmann-json.dir/build.make _deps/repo-third-party-build/CMakeFiles/nlohmann-json.dir/build
.PHONY : nlohmann-json/fast

#=============================================================================
# Target rules for targets named absl

# Build rule for target.
absl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 absl
.PHONY : absl

# fast build rule for target.
absl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/absl.dir/build.make _deps/repo-third-party-build/CMakeFiles/absl.dir/build
.PHONY : absl/fast

#=============================================================================
# Target rules for targets named protobuf

# Build rule for target.
protobuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protobuf
.PHONY : protobuf

# fast build rule for target.
protobuf/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/protobuf.dir/build.make _deps/repo-third-party-build/CMakeFiles/protobuf.dir/build
.PHONY : protobuf/fast

#=============================================================================
# Target rules for targets named re2

# Build rule for target.
re2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re2
.PHONY : re2

# fast build rule for target.
re2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/re2.dir/build.make _deps/repo-third-party-build/CMakeFiles/re2.dir/build
.PHONY : re2/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/googletest.dir/build.make _deps/repo-third-party-build/CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named c-ares

# Build rule for target.
c-ares: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c-ares
.PHONY : c-ares

# fast build rule for target.
c-ares/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/c-ares.dir/build.make _deps/repo-third-party-build/CMakeFiles/c-ares.dir/build
.PHONY : c-ares/fast

#=============================================================================
# Target rules for targets named grpc

# Build rule for target.
grpc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grpc
.PHONY : grpc

# fast build rule for target.
grpc/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/grpc.dir/build.make _deps/repo-third-party-build/CMakeFiles/grpc.dir/build
.PHONY : grpc/fast

#=============================================================================
# Target rules for targets named libevent

# Build rule for target.
libevent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libevent
.PHONY : libevent

# fast build rule for target.
libevent/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/libevent.dir/build.make _deps/repo-third-party-build/CMakeFiles/libevent.dir/build
.PHONY : libevent/fast

#=============================================================================
# Target rules for targets named libevhtp

# Build rule for target.
libevhtp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libevhtp
.PHONY : libevhtp

# fast build rule for target.
libevhtp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/libevhtp.dir/build.make _deps/repo-third-party-build/CMakeFiles/libevhtp.dir/build
.PHONY : libevhtp/fast

#=============================================================================
# Target rules for targets named prometheus-cpp

# Build rule for target.
prometheus-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prometheus-cpp
.PHONY : prometheus-cpp

# fast build rule for target.
prometheus-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/prometheus-cpp.dir/build.make _deps/repo-third-party-build/CMakeFiles/prometheus-cpp.dir/build
.PHONY : prometheus-cpp/fast

#=============================================================================
# Target rules for targets named crc32c

# Build rule for target.
crc32c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crc32c
.PHONY : crc32c

# fast build rule for target.
crc32c/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/crc32c.dir/build.make _deps/repo-third-party-build/CMakeFiles/crc32c.dir/build
.PHONY : crc32c/fast

#=============================================================================
# Target rules for targets named google-cloud-cpp

# Build rule for target.
google-cloud-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 google-cloud-cpp
.PHONY : google-cloud-cpp

# fast build rule for target.
google-cloud-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/google-cloud-cpp.dir/build.make _deps/repo-third-party-build/CMakeFiles/google-cloud-cpp.dir/build
.PHONY : google-cloud-cpp/fast

#=============================================================================
# Target rules for targets named azure-sdk

# Build rule for target.
azure-sdk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 azure-sdk
.PHONY : azure-sdk

# fast build rule for target.
azure-sdk/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/azure-sdk.dir/build.make _deps/repo-third-party-build/CMakeFiles/azure-sdk.dir/build
.PHONY : azure-sdk/fast

#=============================================================================
# Target rules for targets named cnmem

# Build rule for target.
cnmem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnmem
.PHONY : cnmem

# fast build rule for target.
cnmem/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/cnmem.dir/build.make _deps/repo-third-party-build/CMakeFiles/cnmem.dir/build
.PHONY : cnmem/fast

#=============================================================================
# Target rules for targets named aws-sdk-cpp

# Build rule for target.
aws-sdk-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aws-sdk-cpp
.PHONY : aws-sdk-cpp

# fast build rule for target.
aws-sdk-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/aws-sdk-cpp.dir/build.make _deps/repo-third-party-build/CMakeFiles/aws-sdk-cpp.dir/build
.PHONY : aws-sdk-cpp/fast

#=============================================================================
# Target rules for targets named opentelemetry-cpp

# Build rule for target.
opentelemetry-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opentelemetry-cpp
.PHONY : opentelemetry-cpp

# fast build rule for target.
opentelemetry-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-third-party-build/CMakeFiles/opentelemetry-cpp.dir/build.make _deps/repo-third-party-build/CMakeFiles/opentelemetry-cpp.dir/build
.PHONY : opentelemetry-cpp/fast

#=============================================================================
# Target rules for targets named triton-core-serverstub

# Build rule for target.
triton-core-serverstub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triton-core-serverstub
.PHONY : triton-core-serverstub

# fast build rule for target.
triton-core-serverstub/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/build.make _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/build
.PHONY : triton-core-serverstub/fast

#=============================================================================
# Target rules for targets named triton-core

# Build rule for target.
triton-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triton-core
.PHONY : triton-core

# fast build rule for target.
triton-core/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-core-build/CMakeFiles/triton-core.dir/build.make _deps/repo-core-build/CMakeFiles/triton-core.dir/build
.PHONY : triton-core/fast

#=============================================================================
# Target rules for targets named generic-server-wheel

# Build rule for target.
generic-server-wheel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generic-server-wheel
.PHONY : generic-server-wheel

# fast build rule for target.
generic-server-wheel/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-core-build/python/CMakeFiles/generic-server-wheel.dir/build.make _deps/repo-core-build/python/CMakeFiles/generic-server-wheel.dir/build
.PHONY : generic-server-wheel/fast

#=============================================================================
# Target rules for targets named python-bindings

# Build rule for target.
python-bindings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 python-bindings
.PHONY : python-bindings

# fast build rule for target.
python-bindings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/repo-core-build/python/tritonserver/CMakeFiles/python-bindings.dir/build.make _deps/repo-core-build/python/tritonserver/CMakeFiles/python-bindings.dir/build
.PHONY : python-bindings/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... absl"
	@echo "... aws-sdk-cpp"
	@echo "... azure-sdk"
	@echo "... c-ares"
	@echo "... cnmem"
	@echo "... crc32c"
	@echo "... curl"
	@echo "... generic-server-wheel"
	@echo "... google-cloud-cpp"
	@echo "... googletest"
	@echo "... grpc"
	@echo "... grpc-repo"
	@echo "... libevent"
	@echo "... libevhtp"
	@echo "... nlohmann-json"
	@echo "... opentelemetry-cpp"
	@echo "... prometheus-cpp"
	@echo "... protobuf"
	@echo "... re2"
	@echo "... triton-core"
	@echo "... triton-server"
	@echo "... python-bindings"
	@echo "... triton-core-serverstub"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

